In [1]:
from tensorflow.keras.models import load_model
loaded_model = load_model('model.h5')


loaded_model.summary()

c:\Users\Charanjeet Juneja\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:99: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 148, 148, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 74, 74, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 72, 72, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 36, 36, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 34, 34, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 17, 17, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 15, 15, 128)    │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 7, 7, 128)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 6272)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 512)            │     3,211,776 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 38)             │        19,494 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,472,104 (13.25 MB)

 Trainable params: 3,472,102 (13.25 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2 (12.00 B)

#### I GOT THE MODEL WHICH I MADE IN GOOGLE COLAB

In [2]:
import json
with open("training_hist.json","r") as f:
    data=json.load(f)

In [3]:
for key, value in data.items():
    print(key + ":")
    for v in value:
        print(v)
    print()

loss:
1.010542392730713
0.307609885931015
0.19398264586925507
0.14014725387096405
0.10855548828840256
0.09341824054718018
0.07808179408311844
0.07141537964344025
0.06960716843605042
0.059834498912096024

accuracy:
0.6958569884300232
0.9002746939659119
0.9354994893074036
0.9529339671134949
0.9637362360954285
0.9693295359611511
0.9745954275131226
0.976858377456665
0.9780254364013672
0.9817115664482117

val_loss:
0.4361322224140167
0.3151673972606659
0.22414042055606842
0.22295071184635162
0.19816844165325165
0.1940544694662094
0.301788330078125
0.20501038432121277
0.29289138317108154
0.23095403611660004

val_accuracy:
0.8621357083320618
0.8954348564147949
0.9254895448684692
0.9279940724372864
0.9414275884628296
0.9405737519264221
0.9218465685844421
0.9446721076965332
0.9297017455101013
0.9431352615356445



#### SO ABOVE REPRSENTS HOW MY COLUMNS VARY IN EACH AND EVERY MANNER

In [5]:
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
train_datagen=ImageDataGenerator(rescale=1./255)
validation_datagen=ImageDataGenerator(rescale=1./255)

In [6]:
batch_size = 32
image_size = (150, 150)

In [7]:
train_generator = train_datagen.flow_from_directory(
    'train',
    target_size=image_size,
    batch_size=batch_size,
    class_mode='categorical')

validation_generator = validation_datagen.flow_from_directory(
    'valid',
    target_size=image_size,
    batch_size=batch_size,
    class_mode='categorical')

Found 70295 images belonging to 38 classes.
Found 17572 images belonging to 38 classes.


In [14]:
os.listdir('train')

['Apple___Apple_scab',
 'Apple___Black_rot',
 'Apple___Cedar_apple_rust',
 'Apple___healthy',
 'Blueberry___healthy',
 'Cherry_(including_sour)___healthy',
 'Cherry_(including_sour)___Powdery_mildew',
 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot',
 'Corn_(maize)___Common_rust_',
 'Corn_(maize)___healthy',
 'Corn_(maize)___Northern_Leaf_Blight',
 'Grape___Black_rot',
 'Grape___Esca_(Black_Measles)',
 'Grape___healthy',
 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)',
 'Orange___Haunglongbing_(Citrus_greening)',
 'Peach___Bacterial_spot',
 'Peach___healthy',
 'Pepper,_bell___Bacterial_spot',
 'Pepper,_bell___healthy',
 'Potato___Early_blight',
 'Potato___healthy',
 'Potato___Late_blight',
 'Raspberry___healthy',
 'Soybean___healthy',
 'Squash___Powdery_mildew',
 'Strawberry___healthy',
 'Strawberry___Leaf_scorch',
 'Tomato___Bacterial_spot',
 'Tomato___Early_blight',
 'Tomato___healthy',
 'Tomato___Late_blight',
 'Tomato___Leaf_Mold',
 'Tomato___Septoria_leaf_spot',
 'Tomato___Spid

In [16]:
test_generator = validation_datagen.flow_from_directory(
    'valid',
    target_size=image_size,
    batch_size=batch_size,
    class_mode='categorical',
    shuffle=False
)

Found 17572 images belonging to 38 classes.


In [17]:
predicted_y_value=loaded_model.predict(test_generator)

c:\Users\Charanjeet Juneja\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:122: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


550/550 ━━━━━━━━━━━━━━━━━━━━ 193s 350ms/step


In [18]:
predicted_y_value

array([[9.99742687e-01, 1.43913284e-11, 3.20776023e-12, ...,
        1.37512754e-19, 1.43489872e-14, 8.73193740e-10],
       [1.00000000e+00, 9.29123389e-10, 6.38917001e-12, ...,
        7.72836613e-26, 1.74193335e-17, 7.49125849e-15],
       [1.00000000e+00, 2.75423907e-16, 2.55120262e-16, ...,
        6.03159493e-32, 1.77418318e-25, 1.21330364e-17],
       ...,
       [2.54080561e-08, 5.95703327e-22, 5.42784429e-10, ...,
        3.18571209e-15, 1.36486620e-14, 9.89745319e-01],
       [2.22798060e-12, 4.14184138e-27, 6.44121207e-15, ...,
        2.09727475e-15, 1.43332128e-20, 1.00000000e+00],
       [2.95866416e-23, 2.27663553e-23, 4.11500772e-23, ...,
        2.14155872e-23, 1.75902397e-18, 9.99983191e-01]], dtype=float32)

In [19]:
predicted_y_value.shape

(17572, 38)

In [20]:
predicted_categories=tf.argmax(predicted_y_value,axis=1)

In [21]:
predicted_categories

<tf.Tensor: shape=(17572,), dtype=int64, numpy=array([ 0,  0,  0, ..., 37, 37, 37], dtype=int64)>

In [22]:
predicted_categories.shape

TensorShape([17572])

In [24]:
for x,y in test_generator:
    print(x,x.shape)
    print(y,y.shape)
    print()
    break

[[[[0.5137255  0.47450984 0.5058824 ]
   [0.5254902  0.48627454 0.5176471 ]
   [0.60784316 0.5686275  0.6       ]
   ...
   [0.67058825 0.64705884 0.6627451 ]
   [0.5803922  0.5568628  0.57254905]
   [0.5294118  0.5058824  0.52156866]]

  [[0.5882353  0.54901963 0.5803922 ]
   [0.5176471  0.4784314  0.50980395]
   [0.654902   0.6156863  0.64705884]
   ...
   [0.72156864 0.69803923 0.7137255 ]
   [0.70980394 0.6862745  0.7019608 ]
   [0.63529414 0.6117647  0.627451  ]]

  [[0.49803925 0.454902   0.48627454]
   [0.47450984 0.43137258 0.46274513]
   [0.6117647  0.5686275  0.6       ]
   ...
   [0.61960787 0.59607846 0.6117647 ]
   [0.63529414 0.6117647  0.627451  ]
   [0.5921569  0.5686275  0.58431375]]

  ...

  [[0.6313726  0.6        0.6509804 ]
   [0.59607846 0.5647059  0.6156863 ]
   [0.5882353  0.5568628  0.60784316]
   ...
   [0.70980394 0.6901961  0.7176471 ]
   [0.7607844  0.7411765  0.7686275 ]
   [0.8117648  0.79215693 0.8196079 ]]

  [[0.6392157  0.60784316 0.65882355]
   [0.6

In [26]:
true_categores=tf.concat([y for x,y in test_generator],axis=0)

KeyboardInterrupt: 

In [ ]:
y_true=tf.argmax(true_categores,axis=1)

In [42]:
import numpy as np
from tensorflow.keras.preprocessing import image
img_path = r'train\Apple___Cedar_apple_rust\0a41c25a-f9a6-4c34-8e5c-7f89a6ac4c40___FREC_C.Rust 9807_90deg.JPG'  # Change this to the path of your image
img = image.load_img(img_path, target_size=(150, 150))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)  

img_array /= 255.0

predictions = loaded_model.predict(img_array)

predicted_class_index = np.argmax(predictions)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step


In [43]:
predicted_class_index

2

In [35]:
list_of_classes=os.listdir('train')

In [44]:
list_of_classes[2]

'Apple___Cedar_apple_rust'

In [45]:
list_of_classes

['Apple___Apple_scab',
 'Apple___Black_rot',
 'Apple___Cedar_apple_rust',
 'Apple___healthy',
 'Blueberry___healthy',
 'Cherry_(including_sour)___healthy',
 'Cherry_(including_sour)___Powdery_mildew',
 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot',
 'Corn_(maize)___Common_rust_',
 'Corn_(maize)___healthy',
 'Corn_(maize)___Northern_Leaf_Blight',
 'Grape___Black_rot',
 'Grape___Esca_(Black_Measles)',
 'Grape___healthy',
 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)',
 'Orange___Haunglongbing_(Citrus_greening)',
 'Peach___Bacterial_spot',
 'Peach___healthy',
 'Pepper,_bell___Bacterial_spot',
 'Pepper,_bell___healthy',
 'Potato___Early_blight',
 'Potato___healthy',
 'Potato___Late_blight',
 'Raspberry___healthy',
 'Soybean___healthy',
 'Squash___Powdery_mildew',
 'Strawberry___healthy',
 'Strawberry___Leaf_scorch',
 'Tomato___Bacterial_spot',
 'Tomato___Early_blight',
 'Tomato___healthy',
 'Tomato___Late_blight',
 'Tomato___Leaf_Mold',
 'Tomato___Septoria_leaf_spot',
 'Tomato___Spid

In [46]:
import numpy as np
from tensorflow.keras.preprocessing import image
img_path = r'train\Apple___Cedar_apple_rust\0a41c25a-f9a6-4c34-8e5c-7f89a6ac4c40___FREC_C.Rust 9807_90deg.JPG'  # Change this to the path of your image
img = image.load_img(img_path, target_size=(150, 150))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)  

img_array /= 255.0

predictions = loaded_model.predict(img_array)

predicted_class_index = np.argmax(predictions)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 293ms/step


In [47]:
list_of_classes[predicted_class_index]

'Apple___Cedar_apple_rust'

NOW THE SOLUTION OF THIS PREDICTION

In [51]:
with open("disease_mapping.json", "r") as f:
    disease_mapping = json.load(f)
print(disease_mapping)

{'diseases': {'Apple___Apple_scab': ['Treat with fungicides', 'Prune infected branches', 'Improve air circulation around trees'], 'Apple___Black_rot': ['Remove and destroy infected fruits', 'Apply fungicides', 'Prune to improve air circulation'], 'Apple___Cedar_apple_rust': ['Prune infected branches', 'Apply fungicides', 'Remove nearby cedar trees if possible'], 'Apple___healthy': ['No action needed, monitor for changes'], 'Blueberry___healthy': ['No action needed, monitor for changes'], 'Cherry_(including_sour)___healthy': ['No action needed, monitor for changes'], 'Cherry_(including_sour)___Powdery_mildew': ['Apply fungicides', 'Prune to improve air circulation', 'Remove and destroy infected leaves'], 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot': ['Rotate crops', 'Plant resistant varieties', 'Apply fungicides'], 'Corn_(maize)___Common_rust_': ['Rotate crops', 'Plant resistant varieties', 'Apply fungicides'], 'Corn_(maize)___healthy': ['No action needed, monitor for changes'],

In [54]:
predicted_class = list_of_classes[predicted_class_index]

In [57]:
if predicted_class in disease_mapping["diseases"]:
    disease_solution = disease_mapping["diseases"][predicted_class]
    print("These are the solutions for", predicted_class, "which you can use so that your crop remains free from any danger")
    for idx, solution in enumerate(disease_solution, start=1):
        print("Point {}: {}".format(idx, solution))
else:
    print("No solution found for", predicted_class)

These are the solutions for Apple___Cedar_apple_rust which you can use so that your crop remains free from any danger
Point 1: Prune infected branches
Point 2: Apply fungicides
Point 3: Remove nearby cedar trees if possible
